const MODULE_1 = new Module([
  new Block(BLOCK_SIZE * 1, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 2, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 3, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 4, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 4, canvas.clientHeight / 2 + BLOCK_SIZE),

  new Block(BLOCK_SIZE * 7, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 8, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 9, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 10, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 11, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Spike(BLOCK_SIZE * 11, canvas.clientHeight / 2),
  new Block(BLOCK_SIZE * 12, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 13, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 14, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 15, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 16, canvas.clientHeight / 2 + BLOCK_SIZE),

  new Block(BLOCK_SIZE * 19, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 20, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 21, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 22, canvas.clientHeight / 2 + BLOCK_SIZE),
  new Block(BLOCK_SIZE * 23, canvas.clientHeight / 2 + BLOCK_SIZE),
]);
